// History detail — tapping a saved diagnosis opens the SAME output the
// Diagnose flow showed (PredictionResult), plus when/where it was taken and
// a Share action so the report can be shown to anyone (agronomist, buyer…).
//
// Photo source: the local file when it still exists on this device, else the
// server copy the sync uploaded (GET /history/{id}/photo) — merged entries
// from another device have no imageUri but do have has_photo.
import React, { useEffect, useMemo, useState } from "react";
import {
  Image,
  Modal,
  Pressable,
  ScrollView,
  Share,
  StyleSheet,
  View,
} from "react-native";
import { Text } from "react-native-paper";
import { MaterialIcons } from "@expo/vector-icons";
import axios from "axios";
import { API_BASE } from "../hooks/useApi";
import PredictionResult from "./PredictionResult";
import { useColors } from "../theme";
import { useT } from "../i18n";
import { relativeTime } from "../utils/relativeTime";

function pct(x) {
  if (x == null) return "—";
  const v = x <= 1 ? x * 100 : x;
  return `${v.toFixed(1)}%`;
}

function formatCoords(loc) {
  if (!loc || loc.lat == null || loc.lon == null) return null;
  const parts = [`${loc.lat}, ${loc.lon}`];
  if (loc.accuracy != null) parts.push(`±${loc.accuracy}m`);
  return parts.join(" ");
}

/** Plain-text report for the OS share sheet (works without images). */
function buildReport(item, t, where) {
  const lines = [
    "PotatoDoc — Diagnosis Report",
    "",
    `${t("Result")}: ${item.class} (${pct(item.confidence)})`,
    `${t("Model")}: ${item.model || "—"}`,
    `${t("Taken on")}: ${item.timestamp || "—"}`,
  ];
  if (where) lines.push(`${t("Location")}: ${where}`);
  const probs = item.probabilities || {};
  const keys = Object.keys(probs);
  if (keys.length) {
    lines.push("", t("Per-Class Probabilities") + ":");
    keys.forEach((k) => lines.push(`  ${k}: ${pct(probs[k])}`));
  }
  lines.push("", "— Generated by PotatoDoc");
  return lines.join("\n");
}

const makeStyles = (C) =>
  StyleSheet.create({
    backdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.55)",
      justifyContent: "flex-end",
    },
    sheet: {
      backgroundColor: C.page,
      borderTopLeftRadius: 22,
      borderTopRightRadius: 22,
      maxHeight: "92%",
      paddingBottom: 20,
    },
    grab: {
      alignSelf: "center",
      width: 44,
      height: 5,
      borderRadius: 3,
      backgroundColor: C.cardBorder,
      marginTop: 10,
      marginBottom: 4,
    },
    head: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    headTitle: { flex: 1, fontSize: 17, fontWeight: "800", color: C.ink },
    closeBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: C.card,
      borderWidth: 1,
      borderColor: C.cardBorder,
      alignItems: "center",
      justifyContent: "center",
    },
    photoWrap: { alignItems: "center", marginBottom: 4 },
    photo: { width: 200, height: 200, borderRadius: 14 },
    photoMissing: {
      width: 200,
      height: 120,
      borderRadius: 14,
      backgroundColor: C.leafBg,
      borderWidth: 1,
      borderColor: C.cardBorder,
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    photoMissingText: { fontSize: 12.5, fontWeight: "600", color: C.gray },
    metaCard: {
      backgroundColor: C.card,
      borderWidth: 1,
      borderColor: C.cardBorder,
      borderRadius: 14,
      margin: 16,
      padding: 12,
      gap: 8,
    },
    metaRow: { flexDirection: "row", alignItems: "center", gap: 8 },
    metaText: { flex: 1, fontSize: 13, fontWeight: "600", color: C.ink },
    metaMuted: { fontSize: 12, fontWeight: "500", color: C.gray },
    shareBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: C.primary,
      borderRadius: 14,
      marginHorizontal: 16,
      paddingVertical: 13,
      marginTop: 4,
    },
    shareText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" },
    // PredictionResult renders its own Paper card — trim its outer margin so
    // it sits flush inside the sheet.
    result: { marginTop: 0, marginBottom: 8 },
  });

function Photo({ item, token, s, C, t }) {
  const [uri, setUri] = useState(item.imageUri || null);
  const [missing, setMissing] = useState(false);

  useEffect(() => {
    let alive = true;
    setUri(item.imageUri || null);
    setMissing(false);
    // No local file (merged from another device): pull the server copy.
    if (!item.imageUri && item.has_photo && token && item.id != null) {
      (async () => {
        try {
          const res = await axios.get(
            `${API_BASE}/history/${encodeURIComponent(item.id)}/photo`,
            {
              headers: { Authorization: `Bearer ${token}` },
              responseType: "arraybuffer",
              timeout: 20000,
            }
          );
          const bytes = new Uint8Array(res.data);
          let bin = "";
          const CHUNK = 0x8000;
          for (let i = 0; i < bytes.length; i += CHUNK) {
            bin += String.fromCharCode.apply(null, bytes.subarray(i, i + CHUNK));
          }
          if (alive) setUri(`data:image/jpeg;base64,${btoa(bin)}`);
        } catch (e) {
          if (alive) setMissing(true);
        }
      })();
    } else if (!item.imageUri) {
      setMissing(true);
    }
    return () => {
      alive = false;
    };
  }, [item, token]);

  if (uri) {
    return (
      <View style={s.photoWrap}>
        <Image source={{ uri }} style={s.photo} resizeMode="cover" />
      </View>
    );
  }
  if (missing) {
    return (
      <View style={s.photoWrap}>
        <View style={s.photoMissing}>
          <MaterialIcons name="image-not-supported" size={26} color={C.gray} />
          <Text style={s.photoMissingText}>{t("Photo not on this device")}</Text>
        </View>
      </View>
    );
  }
  return null; // fetching — the sheet still renders the rest immediately
}

export default function HistoryDetailModal({ item, visible, onClose, token }) {
  const C = useColors();
  const t = useT();
  const s = useMemo(() => makeStyles(C), [C]);

  const where =
    item && item.location
      ? [item.location.label, formatCoords(item.location)].filter(Boolean).join(" · ")
      : "";

  const onShare = async () => {
    if (!item) return;
    try {
      await Share.share({ message: buildReport(item, t, where) });
    } catch (e) {
      console.warn("share failed", e?.message);
    }
  };

  if (!item) return null;

  return (
    <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}>
      <Pressable style={s.backdrop} onPress={onClose}>
        <Pressable style={s.sheet} onPress={(e) => e.stopPropagation()}>
          <View style={s.grab} />
          <View style={s.head}>
            <Text style={s.headTitle}>{t("Diagnosis report")}</Text>
            <Pressable style={s.closeBtn} onPress={onClose} hitSlop={8}>
              <MaterialIcons name="close" size={18} color={C.ink} />
            </Pressable>
          </View>

          {/* flexShrink lets the scroll area fit the 92%-max sheet instead of
              growing to full content height (which clipped it and killed scroll). */}
          <ScrollView style={{ flexShrink: 1 }}>
            <Photo item={item} token={token} s={s} C={C} t={t} />

            <View style={s.metaCard}>
              <View style={s.metaRow}>
                <MaterialIcons name="event" size={15} color={C.primary} />
                <Text style={s.metaText}>{item.timestamp || "—"}</Text>
                <Text style={s.metaMuted}>
                  {relativeTime(item.created_at || item.updated_at)}
                </Text>
              </View>
              <View style={s.metaRow}>
                <MaterialIcons name="location-on" size={15} color={C.primary} />
                <Text style={[s.metaText, !where && { color: C.gray }]}>
                  {where || t("No location tag")}
                </Text>
              </View>
              <View style={s.metaRow}>
                <MaterialIcons name="psychology" size={15} color={C.primary} />
                <Text style={s.metaText}>{item.model || "—"}</Text>
              </View>
            </View>

            {/* The exact output the Diagnose flow rendered for this result. */}
            <PredictionResult
              data={item}
              modelLabel={item.model}
              heatmap={null}
              ensembleHeatmaps={null}
            />

            <Pressable style={s.shareBtn} onPress={onShare}>
              <MaterialIcons name="share" size={18} color="#FFFFFF" />
              <Text style={s.shareText}>{t("Share report")}</Text>
            </Pressable>
            <View style={{ height: 8 }} />
          </ScrollView>
        </Pressable>
      </Pressable>
    </Modal>
  );
}
