// History detail — tapping a saved diagnosis opens the SAME output the
// Diagnose flow showed (PredictionResult), plus when/where it was taken and
// a Share action so the report can be shown to anyone (agronomist, buyer…).
//
// Photo source: the local file when it still exists on this device, else the
// server copy the sync uploaded (GET /history/{id}/photo) — merged entries
// from another device have no imageUri but do have has_photo.
//
// Layout: the sheet is a fixed-height column (max 92%) whose middle child is
// the only scrollable region. Share sits in a pinned footer OUTSIDE that
// region, so it can never be scrolled out of reach or clipped by the sheet.
import React, { useEffect, useMemo, useRef, useState } from "react";
import {
  Image,
  Modal,
  Pressable,
  ScrollView,
  Share,
  StyleSheet,
  View,
} from "react-native";
import { Text } from "react-native-paper";
import { MaterialIcons } from "@expo/vector-icons";
import axios from "axios";
import { captureRef } from "react-native-view-shot";
import * as Sharing from "expo-sharing";
import { API_BASE } from "../hooks/useApi";
import PredictionResult from "./PredictionResult";
import ShareReportCard from "./ShareReportCard";
import { useColors } from "../theme";
import { useT } from "../i18n";
import { relativeTime } from "../utils/relativeTime";

function pct(x) {
  if (x == null) return "—";
  const v = x <= 1 ? x * 100 : x;
  return `${v.toFixed(1)}%`;
}

function formatCoords(loc) {
  if (!loc || loc.lat == null || loc.lon == null) return null;
  const parts = [`${loc.lat}, ${loc.lon}`];
  if (loc.accuracy != null) parts.push(`±${loc.accuracy}m`);
  return parts.join(" ");
}

/** Plain-text report — the fallback when the OS can't take an image share. */
function buildReport(item, t, where) {
  const lines = [
    "PotatoDoc — Diagnosis Report",
    "",
    `${t("Result")}: ${item.class} (${pct(item.confidence)})`,
    `${t("Model")}: ${item.model || "—"}`,
    `${t("Taken on")}: ${item.timestamp || "—"}`,
  ];
  if (where) lines.push(`${t("Location")}: ${where}`);
  const probs = item.probabilities || {};
  const keys = Object.keys(probs);
  if (keys.length) {
    lines.push("", t("Per-Class Probabilities") + ":");
    keys.forEach((k) => lines.push(`  ${k}: ${pct(probs[k])}`));
  }
  lines.push("", "— Generated by PotatoDoc");
  return lines.join("\n");
}

/**
 * Local file if it is still on this device, otherwise the server copy the
 * sync uploaded. Shared by the sheet's preview and the offscreen share card
 * so the same bytes are fetched once and cached by RN's image cache.
 */
function usePhotoUri(item, token) {
  const [uri, setUri] = useState(item?.imageUri || null);
  const [missing, setMissing] = useState(false);

  useEffect(() => {
    let alive = true;
    setUri(item?.imageUri || null);
    setMissing(false);
    if (item?.imageUri) return () => { alive = false; };

    // No local file (merged from another device): pull the server copy.
    if (item?.has_photo && token && item.id != null) {
      (async () => {
        try {
          const res = await axios.get(
            `${API_BASE}/history/${encodeURIComponent(item.id)}/photo`,
            {
              headers: { Authorization: `Bearer ${token}` },
              responseType: "arraybuffer",
              timeout: 20000,
            }
          );
          const bytes = new Uint8Array(res.data);
          let bin = "";
          const CHUNK = 0x8000;
          for (let i = 0; i < bytes.length; i += CHUNK) {
            bin += String.fromCharCode.apply(null, bytes.subarray(i, i + CHUNK));
          }
          if (alive) setUri(`data:image/jpeg;base64,${btoa(bin)}`);
        } catch (e) {
          if (alive) setMissing(true);
        }
      })();
    } else {
      setMissing(true);
    }
    return () => { alive = false; };
  }, [item, token]);

  return { uri, missing };
}

const makeStyles = (C) =>
  StyleSheet.create({
    backdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.55)",
      justifyContent: "flex-end",
    },
    sheet: {
      backgroundColor: C.page,
      borderTopLeftRadius: 22,
      borderTopRightRadius: 22,
      maxHeight: "92%",
      overflow: "hidden",
      flexDirection: "column",
    },
    grab: {
      alignSelf: "center",
      width: 44,
      height: 5,
      borderRadius: 3,
      backgroundColor: C.cardBorder,
      marginTop: 10,
      marginBottom: 4,
    },
    head: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    headTitle: { flex: 1, fontSize: 17, fontWeight: "800", color: C.ink },
    closeBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: C.card,
      borderWidth: 1,
      borderColor: C.cardBorder,
      alignItems: "center",
      justifyContent: "center",
    },
    // The ONLY scrollable region: shrinks when the sheet hits its 92% cap,
    // otherwise takes its natural height.
    scroll: { flexShrink: 1 },
    scrollContent: { paddingBottom: 12 },
    photoWrap: { alignItems: "center", marginBottom: 4 },
    photo: { width: 200, height: 200, borderRadius: 14 },
    photoMissing: {
      width: 200,
      height: 120,
      borderRadius: 14,
      backgroundColor: C.leafBg,
      borderWidth: 1,
      borderColor: C.cardBorder,
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    photoMissingText: { fontSize: 12.5, fontWeight: "600", color: C.gray },
    metaCard: {
      backgroundColor: C.card,
      borderWidth: 1,
      borderColor: C.cardBorder,
      borderRadius: 14,
      margin: 16,
      padding: 12,
      gap: 8,
    },
    metaRow: { flexDirection: "row", alignItems: "center", gap: 8 },
    metaText: { flex: 1, fontSize: 13, fontWeight: "600", color: C.ink },
    metaMuted: { fontSize: 12, fontWeight: "500", color: C.gray },
    // Pinned footer — outside the ScrollView, so it is always reachable.
    footer: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: C.cardBorder,
      backgroundColor: C.page,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 18,
    },
    shareBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: C.primary,
      borderRadius: 14,
      paddingVertical: 13,
    },
    shareText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" },
    // Capture target for the share image: laid out offscreen so it never
    // appears in the UI. captureRef draws the view itself (parent clipping
    // does not apply), so this is safe on both platforms.
    offscreen: { position: "absolute", left: -100000, top: 0 },
  });

function Photo({ uri, missing, s, C, t }) {
  if (uri) {
    return (
      <View style={s.photoWrap}>
        <Image source={{ uri }} style={s.photo} resizeMode="cover" />
      </View>
    );
  }
  if (missing) {
    return (
      <View style={s.photoWrap}>
        <View style={s.photoMissing}>
          <MaterialIcons name="image-not-supported" size={26} color={C.gray} />
          <Text style={s.photoMissingText}>{t("Photo not on this device")}</Text>
        </View>
      </View>
    );
  }
  return null; // fetching — the sheet still renders the rest immediately
}

export default function HistoryDetailModal({ item, visible, onClose, token }) {
  const C = useColors();
  const t = useT();
  const s = useMemo(() => makeStyles(C), [C]);
  const cardRef = useRef(null);
  const { uri: photoUri, missing } = usePhotoUri(item, token);
  const [sharing, setSharing] = useState(false);

  const where =
    item && item.location
      ? [item.location.label, formatCoords(item.location)].filter(Boolean).join(" · ")
      : "";

  const onShare = async () => {
    if (!item || sharing) return;
    setSharing(true);
    try {
      // 1. Preferred: a branded PNG of the report.
      try {
        // Give the offscreen card's <Image> a beat to decode before capture.
        await new Promise((r) => setTimeout(r, 350));
        const uri = await captureRef(cardRef, {
          format: "png",
          quality: 1,
          result: "tmpfile",
        });
        if (uri && (await Sharing.isAvailableAsync())) {
          await Sharing.shareAsync(uri, {
            mimeType: "image/png",
            dialogTitle: t("Share report"),
            UTI: "public.png",
          });
          return;
        }
      } catch (e) {
        console.warn("image share failed", e?.message);
      }
      // 2. Fallback: the plain-text report — always works.
      await Share.share({ message: buildReport(item, t, where) });
    } catch (e) {
      console.warn("share failed", e?.message);
    } finally {
      setSharing(false);
    }
  };

  if (!item) return null;

  return (
    <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}>
      <Pressable style={s.backdrop} onPress={onClose}>
        <Pressable style={s.sheet} onPress={(e) => e.stopPropagation()}>
          <View style={s.grab} />
          <View style={s.head}>
            <Text style={s.headTitle}>{t("Diagnosis report")}</Text>
            <Pressable style={s.closeBtn} onPress={onClose} hitSlop={8}>
              <MaterialIcons name="close" size={18} color={C.ink} />
            </Pressable>
          </View>

          <ScrollView style={s.scroll} contentContainerStyle={s.scrollContent}>
            <Photo uri={photoUri} missing={missing} s={s} C={C} t={t} />

            <View style={s.metaCard}>
              <View style={s.metaRow}>
                <MaterialIcons name="event" size={15} color={C.primary} />
                <Text style={s.metaText}>{item.timestamp || "—"}</Text>
                <Text style={s.metaMuted}>
                  {relativeTime(item.created_at || item.updated_at)}
                </Text>
              </View>
              <View style={s.metaRow}>
                <MaterialIcons name="location-on" size={15} color={C.primary} />
                <Text style={[s.metaText, !where && { color: C.gray }]}>
                  {where || t("No location tag")}
                </Text>
              </View>
              <View style={s.metaRow}>
                <MaterialIcons name="psychology" size={15} color={C.primary} />
                <Text style={s.metaText}>{item.model || "—"}</Text>
              </View>
            </View>

            {/* The exact output the Diagnose flow rendered for this result. */}
            <PredictionResult
              data={item}
              modelLabel={item.model}
              heatmap={null}
              ensembleHeatmaps={null}
            />
          </ScrollView>

          {/* Pinned footer: reachable no matter how long the report is. */}
          <View style={s.footer}>
            <Pressable
              style={[s.shareBtn, sharing && { opacity: 0.6 }]}
              onPress={onShare}
              disabled={sharing}
            >
              <MaterialIcons name="share" size={18} color="#FFFFFF" />
              <Text style={s.shareText}>
                {sharing ? t("Sharing…") : t("Share report")}
              </Text>
            </Pressable>
          </View>
        </Pressable>
      </Pressable>

      {/* Offscreen capture target for the share image. */}
      {visible ? (
        <View style={s.offscreen} pointerEvents="none">
          <View ref={cardRef} collapsable={false}>
            <ShareReportCard item={item} where={where} photoUri={photoUri} />
          </View>
        </View>
      ) : null}
    </Modal>
  );
}
