// The branded report card that gets captured to a PNG and handed to the OS
// share sheet. Rendered offscreen inside the detail sheet — it never shows in
// the UI, it only exists to be photographed by react-native-view-shot.
//
// Colours are hard-coded rather than taken from the theme on purpose: a shared
// image must look identical whether the sender is in light or dark mode.
import React, { useMemo } from "react";
import { Image, StyleSheet, Text, View } from "react-native";
import { MaterialIcons } from "@expo/vector-icons";
import { CLASS_COLORS } from "../constants/colors";

const BRAND = {
  deep: "#023422",
  green: "#2E7D32",
  page: "#FAFAF7",
  card: "#FFFFFF",
  line: "#E5E7EB",
  ink: "#1A1A1A",
  gray: "#6B7280",
};

export const SHARE_CARD_WIDTH = 720;

function pct(x) {
  if (x == null) return "—";
  const v = x <= 1 ? x * 100 : x;
  return `${v.toFixed(1)}%`;
}

function barPct(x) {
  if (x == null) return 0;
  const v = x <= 1 ? x * 100 : x;
  return Math.max(0, Math.min(100, v));
}

function Row({ icon, label, value }) {
  return (
    <View style={s.row}>
      <MaterialIcons name={icon} size={16} color={BRAND.green} />
      <Text style={s.rowLabel}>{label}</Text>
      <Text style={s.rowValue} numberOfLines={1}>
        {value || "—"}
      </Text>
    </View>
  );
}

export default function ShareReportCard({ item, where, photoUri }) {
  const classColor = useMemo(
    () => CLASS_COLORS[item?.class] || BRAND.gray,
    [item?.class]
  );

  if (!item) return null;

  const probs = item.probabilities || {};
  const probKeys = Object.keys(probs);
  const unknown = item.is_unknown || item.class === "Unknown";
  const generatedOn = new Date().toLocaleDateString();

  return (
    <View style={s.card}>
      <View style={s.header}>
        <View style={s.logo}>
          <MaterialIcons name="eco" size={26} color="#FFFFFF" />
        </View>
        <View style={{ flex: 1 }}>
          <Text style={s.brand}>POTATODOC</Text>
          <Text style={s.tagline}>Potato Leaf Disease Diagnosis</Text>
        </View>
        <View style={s.headerPill}>
          <Text style={s.headerPillText}>REPORT</Text>
        </View>
      </View>

      <View style={s.body}>
        <View style={s.photoWrap}>
          {photoUri ? (
            <Image source={{ uri: photoUri }} style={s.photo} resizeMode="cover" />
          ) : (
            <View style={[s.photo, s.photoPlaceholder]}>
              <MaterialIcons name="image-not-supported" size={40} color={BRAND.gray} />
              <Text style={s.photoPlaceholderText}>Photo not on this device</Text>
            </View>
          )}
        </View>

        <Text style={s.section}>RESULT</Text>
        <View style={s.resultRow}>
          <Text style={[s.resultName, { color: classColor }]} numberOfLines={1}>
            {item.class}
          </Text>
          <Text style={s.resultConf}>{pct(item.confidence)}</Text>
        </View>
        <View style={s.track}>
          <View
            style={[
              s.fill,
              { width: `${barPct(item.confidence)}%`, backgroundColor: classColor },
            ]}
          />
        </View>
        {unknown ? (
          <Text style={s.unknownNote}>
            {item.message ||
              "This image was not recognised as one of the known potato-leaf classes."}
          </Text>
        ) : null}

        <View style={s.metaBox}>
          <Row icon="event" label="Taken on" value={item.timestamp} />
          <Row icon="location-on" label="Location" value={where} />
          <Row icon="memory" label="Model" value={item.model} />
        </View>

        {probKeys.length > 0 && (
          <>
            <Text style={s.section}>PER-CLASS PROBABILITIES</Text>
            <View style={s.probs}>
              {probKeys.map((k) => {
                const v = probs[k];
                const color = CLASS_COLORS[k] || BRAND.gray;
                return (
                  <View key={k} style={s.probRow}>
                    <Text style={s.probName} numberOfLines={1}>
                      {k}
                    </Text>
                    <View style={s.probTrack}>
                      <View
                        style={[
                          s.probFill,
                          { width: `${barPct(v)}%`, backgroundColor: color },
                        ]}
                      />
                    </View>
                    <Text style={s.probValue}>{pct(v)}</Text>
                  </View>
                );
              })}
            </View>
          </>
        )}
      </View>

      <View style={s.footer}>
        <Text style={s.footerText}>Generated by PotatoDoc</Text>
        <Text style={s.footerText}>{generatedOn}</Text>
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  card: {
    width: SHARE_CARD_WIDTH,
    backgroundColor: BRAND.page,
    borderRadius: 0,
    overflow: "hidden",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: BRAND.deep,
    paddingHorizontal: 28,
    paddingVertical: 22,
  },
  logo: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: BRAND.green,
    alignItems: "center",
    justifyContent: "center",
  },
  brand: { color: "#FFFFFF", fontSize: 24, fontWeight: "900", letterSpacing: 1.6 },
  tagline: { color: "#C9E7CF", fontSize: 13, fontWeight: "600", marginTop: 2 },
  headerPill: {
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  headerPillText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800", letterSpacing: 1.2 },

  body: { paddingHorizontal: 28, paddingTop: 24, paddingBottom: 8 },

  photoWrap: { alignItems: "center", marginBottom: 18 },
  photo: { width: 340, height: 340, borderRadius: 18, backgroundColor: "#E9EFE7" },
  photoPlaceholder: { alignItems: "center", justifyContent: "center", gap: 8 },
  photoPlaceholderText: { color: BRAND.gray, fontSize: 14, fontWeight: "600" },

  section: {
    color: BRAND.gray,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.3,
    marginBottom: 8,
    marginTop: 6,
  },

  resultRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 12,
  },
  resultName: { fontSize: 36, fontWeight: "900", flex: 1 },
  resultConf: { fontSize: 30, fontWeight: "900", color: BRAND.ink },

  track: {
    height: 12,
    borderRadius: 6,
    backgroundColor: "#E7ECE5",
    marginTop: 14,
    overflow: "hidden",
  },
  fill: { height: 12, borderRadius: 6 },
  unknownNote: { color: BRAND.gray, fontSize: 15, lineHeight: 22, marginTop: 12 },

  metaBox: {
    backgroundColor: BRAND.card,
    borderWidth: 1,
    borderColor: BRAND.line,
    borderRadius: 14,
    marginTop: 20,
    paddingVertical: 6,
    paddingHorizontal: 16,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 11,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: BRAND.line,
  },
  rowLabel: { color: BRAND.gray, fontSize: 14, fontWeight: "700", width: 96 },
  rowValue: { flex: 1, color: BRAND.ink, fontSize: 15, fontWeight: "700", textAlign: "right" },

  probs: {
    backgroundColor: BRAND.card,
    borderWidth: 1,
    borderColor: BRAND.line,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 12,
  },
  probRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  probName: { width: 132, color: BRAND.ink, fontSize: 14, fontWeight: "700" },
  probTrack: {
    flex: 1,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#E7ECE5",
    overflow: "hidden",
  },
  probFill: { height: 10, borderRadius: 5 },
  probValue: { width: 64, textAlign: "right", color: BRAND.ink, fontSize: 14, fontWeight: "800" },

  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: BRAND.line,
    backgroundColor: BRAND.card,
    paddingHorizontal: 28,
    paddingVertical: 16,
  },
  footerText: { color: BRAND.gray, fontSize: 13, fontWeight: "700" },
});
